### ISSUE TITLE
!compileandrun causes exception

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [kevingosse/windbg-extensions#4] opened 2020-05-28 21:04 UTC
When executing `!compileandrun`, the extension responds with

```
0:000> !compileandrun
e0434352 Exception in C:\Users\...\AppData\Local\dbg\UIExtensions\CsharpScriptRunner-x64\WindbgScriptRunner.dll.compileandrun debugger extension.
      PC: 00007ff9`c183a799  VA: 00000000`00000000  R/W: 8013150c  Parameter: 00000000`00000000
```

When I debug the extension, I see a WindowsDebugger.SourceNotFoundException bubbling up its way:

```
0:005> !pe
Exception object: 000002263e51d098
Exception type:   WindowsDebugger.SourceNotFoundException
Message:          No source file was found
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131500

0:005> g
(3d1c.4870): CLR exception - code e0434352 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
KERNELBASE!RaiseException+0x69:
00007ff9`c183a799 0f1f440000      nop     dword ptr [rax+rax]

0:000> !pe
Exception object: 000002263e51d098
Exception type:   WindowsDebugger.SourceNotFoundException
Message:          No source file was found
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    000000E0ABC3EC10 00007FF94221D4F2 UNKNOWN!DbgX.Requests.SourceLocationRequest.GetSourceInfo(DbgX.EngineInterfaces, UInt32 ByRef, System.String ByRef)+0x282
    000000E0ABC3ED60 00007FF94221AE30 UNKNOWN!DbgX.Requests.SourceLocationRequest.DoExecute(DbgX.Requests.IEngineRequestServices, DbgX.EngineInterfaces)+0x110
    000000E0ABC3EEA0 00007FF94206B67C UNKNOWN!DbgX.Requests.EngineRequestWithTask`1[[System.__Canon, mscorlib]].Execute(DbgX.Requests.IEngineRequestServices, DbgX.EngineInterfaces)+0x5c
StackTraceString: <none>
HResult: 80131500

0:000> g
(3d1c.4870): CLR exception - code e0434352 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
KERNELBASE!RaiseException+0x69:
00007ff9`c183a799 0f1f440000      nop     dword ptr [rax+rax]

0:000> !pe
Exception object: 000002263e51d098
Exception type:   WindowsDebugger.SourceNotFoundException
Message:          No source file was found
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    000000E0ABC3EC10 00007FF94221D4F2 UNKNOWN!DbgX.Requests.SourceLocationRequest.GetSourceInfo(DbgX.EngineInterfaces, UInt32 ByRef, System.String ByRef)+0x282
    000000E0ABC3ED60 00007FF94221AE30 UNKNOWN!DbgX.Requests.SourceLocationRequest.DoExecute(DbgX.Requests.IEngineRequestServices, DbgX.EngineInterfaces)+0x110
    000000E0ABC3EEA0 00007FF94206B67C UNKNOWN!DbgX.Requests.EngineRequestWithTask`1[[System.__Canon, mscorlib]].Execute(DbgX.Requests.IEngineRequestServices, DbgX.EngineInterfaces)+0x5c
    000000E0AA5EDE60 00007FF9A0318E70 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    000000E0AA5EDE90 00007FF99F9B9AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    000000E0AA5EDEC0 00007FF942219C9C UNKNOWN!DbgX.Debugger.Services.SourceLineService+<GetSourceLineAsync>d__23.MoveNext()+0x2ec

StackTraceString: <none>
HResult: 80131500
```

**Comment by kevingosse** [comment] 2020-08-27 20:27
`!compileandrun` takes the path to a `.cs` source file as parameter. This command is expected to be called only from the UI, but I guess there's no harm on sanitizing it and adding a help message. I'll take care of that.

**Comment by kevingosse** [comment] 2020-08-30 20:28
Actually that's not the error I thought. The one that is thrown when no parameter is provided is:

```
0:000> !compileandrun
An error occured: System.ArgumentException: Empty path name is not legal.
   at System.IO.File.ReadAllText(String path)
   at WindbgScriptRunner.ScriptRunner.Run(IntPtr client, String args) in E:\git\windbg-extensions\src\WinDbgScriptRunner.Shared\ScriptRunner.cs:line 30
```
I wonder what causes yours... I know it's been a while, are you still able to reproduce it?

**Comment by jpdurot** [comment] 2021-04-22 12:16
~~I am facing the same issue from the UI, didn't try to debug, but it looks like no file has been created in my %TEMP% directory. Should I expect to see it in another directory ?
I also tried to run manually the command with a non-existing file, like:
`!compileandrun C:\NonExistingFile.cs`
and faced the exact same error message~~
```
e0434352 Exception in C:\Users\jp.durot\AppData\Local\dbg\UIExtensions\CsharpScriptRunner-x64\WindbgScriptRunner.dll.compileandrun debugger extension.
      PC: 00007ff9`e4373b19  VA: 00000000`00000000  R/W: 8013150c  Parameter: 00000000`00000000
```
EDIT: Actually, it's not true, the file is indeed created, but deleted just after execution. 
But... I get this error even if I don't pass any parameter to the `!compileandrun` command, which is different from what you mentioned in the previous comment.
I managed to attach my VS instance to Windbg, and it fails when executing this line of code:
`ChildDomain.DoCallBack(invoker.Invoke);`
from the CompileAndRun method. The Invoke method is never called.

**Comment by kevingosse** [comment] 2021-05-06 19:46
It's really annoying that I'm not able to reproduce it... I'm pretty sure it's a simple error in managed code. One thing that could help would be to catch it and log to a file (you can't write to the console at this point unfortunately):

```csharp
        [DllExport("compileandrun")]
        public static void CompileAndRun(IntPtr client, [MarshalAs(UnmanagedType.LPStr)] string args)
        {
            try
            {
                if (ChildDomain == null)
                {
                    ChildDomain = AppDomain.CreateDomain("CSharpRunner", AppDomain.CurrentDomain.Evidence, GetAssemblyPath(), ".", false);
                }

                var invoker = new ScriptInvoker(client, args);

                ChildDomain.DoCallBack(invoker.Invoke);
            }
            catch (Exception ex)
            {
                File.WriteAllText(@"C:\someFolder", ex);
            }
        }
```

@jpdurot Any chance you could try that?

**Comment by jpdurot** [comment] 2021-05-31 09:54
Hi @kevingosse, thanks for replying, I think I now understand why it doesn't work
The exception I get when running the updated piece of code is the following: (sorry for future readers, my .Net language pack is in French)
```
System.Runtime.Serialization.SerializationException: Le type n'est pas résolu pour le membre 'WindbgScriptRunner.ScriptInvoker,WindbgScriptRunner, Version=1.0.7821.18167, Culture=neutral, PublicKeyToken=null'.
   à System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   à WindbgScriptRunner.Runner.CompileAndRun(IntPtr client, String args) dans C:\dev\others\windbg-extensions\src\WinDbgScriptRunner.Shared\Runner.cs:ligne 25
```
I then tried to make the `ScriptInvoker` class inheriting from `MarshalByRefObject` (even if it should be useless as it's marked as Serializable) and I got a more detailed exception: (I removed the useless stack trace, but the issue is coming from the same line)
```
System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'WindbgScriptRunner, Version=1.0.7821.20692, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
Nom de fichier : 'WindbgScriptRunner, Version=1.0.7821.20692, Culture=neutral, PublicKeyToken=null'
<useless stack trace>
=== Informations d'état de liaison préalable ===
JRN : DisplayName = WindbgScriptRunner, Version=1.0.7821.20692, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
JRN : Appbase = file:///C:/Users/jp.durot/AppData/Local/Packages/Microsoft.WinDbg_8wekyb3d8bbwe/LocalCache/Local/DBG/UIExtensions/CsharpScriptRunner-x64
JRN : PrivatePath initial = .
Assembly appelant : (Unknown).
```
It seems the Appbase directory does not correspond to the directory my extension has been copied into (from the VS post-build event), and this directory does not even exist on my machine (the VS build actually copy the output to `C:\Users\jp.durot\AppData\Local\DBG\UIExtensions`). The Appbase value corresponds to what is computed in `Runner.GetAssemblyPath()`

After manually copying every file from `C:\Users\jp.durot\AppData\Local\DBG\UIExtensions` to `C:\Users\jp.durot\AppData\Local\Packages\Microsoft.WinDbg_8wekyb3d8bbwe\LocalCache\Local\DBG\UIExtensions`, and also reverting every changes made on the code, it is now working 😄 

Should we udpate the `Runner.GetAssemblyPath()` code to return `%APPDATA%\Local\DBG\UIExtensions` instead ?

**Comment by kevingosse** [comment] 2021-06-02 19:04
Well, what is _supposed_ to happen is:

 - WinDbgExt.RunCSharp.dll is installed into `%LOCALAPPDATA%\DBG\UIExtensions` and loaded by the WinDbg shell
 - When opening the C# editor, CsharpScriptRunner-x64 is extracted from the resources of the assembly into `%LOCALAPPDATA%\DBG\UIExtensions\CsharpScriptRunner-x64` : https://github.com/kevingosse/windbg-extensions/blob/master/src/RunCSharp/OpenEditorViewModel.cs#L56
 - The contents actually get written to `%LOCALAPPDATA%\Packages\Microsoft.WinDbg_8wekyb3d8bbwe\LocalCache\Local\DBG\UIExtensions`. **This happens automatically**, I believe this is because WinDbg uses the Windows Desktop Bridge
 - CsharpScriptRunner-x64 needs then to be loaded by EngHost (a child process spawned by WinDbg). EngHost runs outside of the sandbox, so I need to give it the actual path (`%LOCALAPPDATA%\Packages\Microsoft.WinDbg_8wekyb3d8bbwe\LocalCache\Local\DBG\UIExtensions`) instead of the virtual path (`%LOCALAPPDATA%\DBG\UIExtensions\CsharpScriptRunner-x64`)

On my computer, this is what happens. In your case, it looks like for some reason the write to `%LOCALAPPDATA%\DBG\UIExtensions` is not mirrored to `%LOCALAPPDATA%\Packages\Microsoft.WinDbg_8wekyb3d8bbwe\LocalCache\Local\DBG\UIExtensions`. I have no clue why (I don't actually know how all this isolation works, I got there by trial and error) 🤔 

@jpdurot Can you try changing `Runner.GetAssemblyPath()` to this and see if it fixes the issue? (sorry to ask that, but since I don't know how to reproduce on my machine...)

```csharp
        private static string GetAssemblyPath()
        {
            string basePath;
            
            try
            {
                var suffix = Environment.Is64BitProcess ? "x64" : "x86";

                basePath = Environment.ExpandEnvironmentVariables("%LOCALAPPDATA%\\Packages\\" + Windows.ApplicationModel.Package.Current.Id.FamilyName);
                basePath = Path.Combine(basePath, $@"LocalCache\Local\DBG\UIExtensions\CsharpScriptRunner-{suffix}");

                if (!Directory.Exists(basePath))
                {
                    basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                }
            }
            catch (Exception) // This will throw if running without the Windows Bridge	
            {
                basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            }

            return basePath;
        }
```

**Comment by jpdurot** [comment] 2021-06-02 19:41
Yes, the third step is not done on my machine...
I tried with your updated code and it works 👍 

What could explain this behaviour is that the extension seems to be run from the "main" process (if I want to debug this piece of code, I must attach to `DbgX.Shell.exe`, not `Enghost.exe`)

**Comment by kevingosse** [comment] 2021-06-02 19:45
> I tried with your updated code and it works 👍

Great! I'm going to update the code then. Thanks a lot for the help!

> What could explain this behaviour is that the extension seems to be run from the "main" process (if I want to debug this piece of code, I must attach to `DbgX.Shell.exe`, not `Enghost.exe`)

`GetAssemblyPath` is running in DbgX.Shell.exe? Wow, that's really unexpected. Are you sure of it? The UI extension (the `OpenEditorViewModel` for instance) runs in DbgX.Shell.exe, but the runner is really supposed to run in EngHost.exe 🤔

**Comment by jpdurot** [comment] 2021-06-02 20:11
> `GetAssemblyPath` is running in DbgX.Shell.exe? Wow, that's really unexpected. Are you sure of it? The UI extension (the `OpenEditorViewModel` for instance) runs in DbgX.Shell.exe, but the runner is really supposed to run in EngHost.exe 🤔

My bad... I just double checked as I also found it weird, and it's indeed Enghost.exe that is running the Runner code. I think I was attached to both processes at the same time (as I was able to put breakpoint on both ViewModel and Runner).

**Comment by kevingosse** [comment] 2021-06-02 20:32
Fixed in https://github.com/kevingosse/windbg-extensions/commit/61051c34b79649f37b02de96603ffec84fdffadf (hopefully)

Thanks again for the help!

**Closed as completed by kevingosse** 2021-06-02 20:32 UTC
